### ISSUE TITLE
Clicking a scroll bar inside a header menu closes the menu

### ISSUE THREAD

**Issue by mattboehm** [mleibman/SlickGrid#421]
Include the following css:

``` css
.slick-header-menu {
  max-height:2em;//I suppose this is optional
  overflow:scroll;
}
```

This should cause a scrollbar to appear in the menu. Clicking on this scrollbar (to scroll up/down) causes the menu to disappear.

This is due to this code:

``` javascript
function handleBodyMouseDown(e) {
  if ($menu && !$.contains($menu[0], e.target)) {
    hideMenu();
  }
}
```

`$.contains()` returns false when the scroll bar is clicked on.

Possible solutions:
- Wrap the dropdown menu in another div.  All current styling applies to the inner div but $.contains() checks the outer div (not sure if this would work)
- Use a different method to check if the click is within the menu or not.
- Handle scrolling differently (not with the native browser scrollbar)
